version: 2
jobs:
  lint:
    docker:
      - image: circleci/node:8.5
    steps:
      - checkout
      - run:
          name: npm install
          command: npm install
      - run:
          name: npm run lint
          command: npm run lint
  test:
    docker:
      - image: circleci/node:8.5
    steps:
      - checkout
      - run:
          name: npm install
          command: npm install
      - run:
          name: npm test
          command: npm test
workflows:
  version: 2
  lint:
    jobs:
      - lint
  test:
    jobs:
      - test
